const works = [
    {
        name: "Luciviewer",
        year: "2023",
        company: "Instapath",
        license: "Proprietary",
        descr: "Low-latency deep-zoom viewer for tissue scans",
        tags: ["code"],
        stack: [
            "react.js",
            "next.js",
            "redux",
            "tailwind",
            "docker",
            "typescript",
            "zod",
            "pnpm",
            "turborepo",
        ],
        cover: ["/demo/dev/instapath.png"],
    },
    {
        name: "Instapath",
        year: "2023",
        tags: ["design"],
        cover: ["/demo/design/instapath.png"],
        link: "/internal/instapath",
        rank: 4,
    },
    {
        name: "Upreach Client Work",
        year: "2023",
        tags: ["design"],
        cover: ["/demo/design/upreach.png"],
        link: "/internal/upreachclient",
        rank: 1,
    },
    {
        name: "Mixes",
        year: "2021",
        tags: ["design"],
        cover: ["/demo/design/mixes.png"],
        link: "https://bootcamp.uxdesign.cc/mixing-up-apple-music-ccd070cc0cd5",
        rank: 2,
    },
    {
        name: "Bocaml",
        year: "2023",
        company: "CS 3110: Functional Programming",
        license: "Open Source",
        descr: "GPT-powered multimedia Telegram bot",
        tags: ["code"],
        stack: ["openai", "ocaml", "telegram api"],
        cover: ["/demo/dev/bocaml.png"],
        link: "https://github.com/epicdragon44/g511",
    },
    {
        name: "Yoomi AR",
        year: "2022",
        company: "Yoomi Health",
        license: "Proprietary",
        descr: "Web-based AR gamification for physical therapy",
        tags: ["code"],
        stack: ["typescript", "jest", "opencv"],
        cover: ["/demo/dev/yoomi.png"],
    },
    {
        name: "Cask",
        year: "2022",
        tags: ["design"],
        cover: ["/demo/design/cask.png"],
        link: "https://docs.google.com/presentation/d/e/2PACX-1vQ7-7jmIP36tgjivxXjmCM3WuI61dPft-wCGc1H_0dy203rXDto8_wTgcWiijGGRFBxaRwj8SKcoRv2/pub?start=false&loop=false&delayms=5000",
        rank: 3,
    },
    {
        name: "Fasternet",
        year: "2020",
        company: "HooHacks 2020 Winner",
        license: "Open Source",
        descr: "Instantly halve DNS resolution times on your Windows PC",
        tags: ["code"],
        stack: ["python", "tcl", "powershell"],
        cover: ["/demo/dev/fasternet.png"],
        link: "https://github.com/epicdragon44/fasternet",
    },
    {
        name: "HyperDTI",
        year: "2023",
        company: "Cornell DTI",
        license: "Open Source",
        descr: "Dead simple URL shortener",
        tags: ["code"],
        stack: ["javascript", "svelte", "firebase", "vercel"],
        cover: ["/demo/dev/hyperdti.png"],
        link: "https://hyperdt.in/",
    },
    {
        name: "Trends Autograder",
        year: "2023",
        company: "INFO 1998: Trends in Web Development",
        license: "Open Source",
        descr: "Functional, highly concurrent assignment autograder",
        tags: ["code"],
        stack: ["typescript", "effect-ts", "bun"],
        link: "https://github.com/cornell-dti/trends-autograder",
    },
    {
        name: "Senmonni",
        year: "2020",
        company: "Tecmend LLC",
        license: "Proprietary",
        descr: "Mobile payments app for Belize",
        tags: ["code"],
        stack: ["react native", "quickbooks api", "soap api", "hubspot"],
    },
    {
        name: "WaveLab Recovery",
        year: "2019",
        company: "WaveLab Global, Inc.",
        license: "Proprietary",
        descr: "Desktop program to recover misconfigured network devices",
        tags: ["code"],
        stack: ["java", "c", "swing", "maven", "udp", "tcp/ip"],
    },
];

export default works;
