const works = [
    {
        name: "Luci Viewer",
        year: "2023",
        company: "Instapath",
        license: "Proprietary",
        descr: "Low-latency, AI-powered deep-zoom viewer for tissue scans",
        tags: ["design", "code"],
        stack: [
            "react.js",
            "next.js",
            "redux",
            "node.js",
            "tailwind",
            "docker",
            "typescript",
            "zod",
            "yarn",
        ],
        link: "https://viewer.instapath.app/",
    },
    {
        name: "Mixes",
        year: "2021",
        company: "INFO 1998: Intro to Digital Product Design",
        license: "Open Source",
        descr: "An Apple Music Case Study",
        tags: ["design"],
        stack: ["figma", "medium"],
        link: "https://bootcamp.uxdesign.cc/mixing-up-apple-music-ccd070cc0cd5",
    },
    {
        name: "Cask",
        year: "2022",
        company: "Cornell Fintech Hackathon 2022 Winner",
        license: "Open Source",
        descr: "An NFT Marketplace for Influencers and Creatives",
        tags: ["design"],
        stack: ["figma"],
        link: "https://docs.google.com/presentation/d/1Sq_d0WqInwHX2wj206Hlaiy0j3L07xMHu0oQqDqUrs0/edit?usp=sharing",
    },
    {
        name: "Fasternet",
        year: "2020",
        company: "HooHacks 2020 Winner",
        license: "Open Source",
        descr: "Instantly halve DNS resolution times on your Windows PC",
        tags: ["code"],
        stack: ["python", "tcl", "powershell"],
        link: "https://github.com/epicdragon44/fasternet",
    },
    {
        name: "Internbot",
        year: "2022",
        company: "Cornell DTI",
        license: "Open Source",
        descr: "Scalable internal organization Slackbot",
        tags: ["code"],
        stack: ["javascript", "redis", "jest", "vite", "slack api"],
        link: "https://github.com/cornell-dti/internbot",
    },
    {
        name: "Bocaml",
        year: "2023",
        company: "CS 3110: Functional Programming",
        license: "Open Source",
        descr: "GPT-powered multimedia Telegram bot",
        tags: ["code"],
        stack: ["openai", "ocaml", "telegram api"],
        link: "https://github.com/epicdragon44/g511",
    },
    {
        name: "Yoomi AR",
        year: "2022",
        company: "Yoomi Health",
        license: "Proprietary",
        descr: "Mark Cuban-funded gamification experience for physical therapy patients",
        tags: ["code"],
        stack: ["typescript", "jest", "opencv"],
    },
    {
        name: "Senmonni",
        year: "2020",
        company: "Tecmend LLC",
        license: "Proprietary",
        descr: "Mobile payments app for Belize",
        tags: ["code"],
        stack: ["react native", "quickbooks api", "soap api", "hubspot"],
    },
    {
        name: "WaveLab Recovery Program",
        year: "2019",
        company: "WaveLab Global, Inc.",
        license: "Proprietary",
        descr: "Recover misconfigured IoT devices on a network",
        tags: ["code"],
        stack: ["java", "c", "swing", "maven", "udp", "tcp/ip"],
    },
];

export default works;
